# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwetter', '0002_auto_20170514_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likedTweets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasLiked', to='kwetter.Tweet'),
        ),
    ]
