# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetter', '0004_auto_20170514_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='kwetter.Account'),
        ),
    ]
