# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetter', '0005_account_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='kwetter.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='likedTweets',
            field=models.ManyToManyField(blank=True, related_name='hasLiked', to='kwetter.Tweet'),
        ),
    ]
